project:
  type: book

book:
  title: "Uma Abordagem Assintótica aos Testes de Hipótese"
  author: "Gustavo Almeida Silva"

  page-footer:
    left: |
      Uma Abordagem Assintótica aos Testes de Hipótese foi escrito por Gustavo Almeida Silva
    right: |
      Esse livro foi feito com <a href="https://quarto.org/">Quarto</a>.
  cover-image: image.png
  favicon: favicon.png
  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - lhood.qmd
    - wald.qmd
    - escore.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
pdf:
    documentclass: scrreport

toc-title: Conteúdo
execute:
  warning: false
  message: false
